### ISSUE TITLE
get_theme_mod() returning the old cached value

### ISSUE THREAD

**Issue by ParhamG** [tollmanz/wordpress-pecl-memcached-object-cache#89]
Earlier today I had a weird issue on a WP-network installation which uses this object cache drop-in, and after looking into it I found out that get_theme_mod() is returning the older cached value for a specific key and not the newer value which was updated using set_theme_mod(). I verified that the value was actually updated in the options table though. Triggering set_theme_mod() with the new value on the subsequent requests didn't help and I ended up flushing the object cache for the network to fix this and then wasn't able to reproduce the issue again. What could be the reason for this?

**Comment by szepeviktor** [comment]
Could it be a core bug? Try searching [Trac](https://core.trac.wordpress.org/).

**Comment by tollmanz** [comment]
This is caused by a really nasty [core bug](https://core.trac.wordpress.org/ticket/31245). In many cases, you will experience problems with the cache returning old values. This bug has existed as long as WP has supported an object cache.

I have not taken the time to implement a work around in this library, but I recommend checking out: https://github.com/humanmade/wordpress-pecl-memcached-object-cache/pull/1/files. This shows how to workaround the problem. In fact, I might even recommend just using that fork of this project.
